sudo: required
language: node_js
node_js:
  - '0.12'
branches:
  only:
    - master
    - devel
before_install:
  # fire up xvfb on port :99.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  # get Meteor
  - curl https://install.meteor.com/ | sh
services:
  - mongodb
script:
  - meteor --test
notifications:
  slack:
    rooms:
      - metroidhq:PZZ19xv8VA3fRpveiBcPA1oU
    on_success: always
    on_failure: always