language: node_js

node_js:
  - "0.10"

services:
  - mongodb

cache:
  directories:
    - ~/.meteor

before_install:
  # set up the node_modules dir, so we know where it is
  - "mkdir -p node_modules &"
  # fire up xvfb on port :99.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # set the xvfb screen size to 1280x1024x16
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  # install meteor
  - "curl https://install.meteor.com | /bin/sh"

script:
  bash build.sh

notifications:
  slack:
    rooms:
      - metroidhq:PZZ19xv8VA3fRpveiBcPA1oU
    on_success: always
    on_failure: always