sudo: required
language: node_js
node_js:
  - '0.12'
before_install:
  - curl https://install.meteor.com/ | sh
services:
  - mongodb
script:
  - meteor --test
  - sleep 50
notifications:
  slack:
    rooms:
      - metroidhq:PZZ19xv8VA3fRpveiBcPA1oU
    on_success: always
    on_failure: always